classOrder = [
	"Thread",
    "Value",
    "Property",
    "Animate",
    "Create",
    "Configure",
    "Iterate",
    "DelayValue",
    "Delay",
    "Do",
    "State",
    "Event",
    "Info",
    "SpringInfo",
    "SetTo",
]