[package]
name = "prophetouw/faye"
version = "1.1.0"
registry = "https://github.com/ProphetOuw/Faye"
realm = "shared"
license = "MIT"
description = "reactive UI framework."
[dependencies]
Signal = "prophetouw/simplesignal@1.0.6"